// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCll-PmzXqvT0j5AocEWjN8ESc-l4CaCFU',
    appId: '1:1089220401823:web:26e68e016cbfc4ba76a0aa',
    messagingSenderId: '1089220401823',
    projectId: 'fasilitas-umum-eeb07',
    authDomain: 'fasilitas-umum-eeb07.firebaseapp.com',
    storageBucket: 'fasilitas-umum-eeb07.firebasestorage.app',
    measurementId: 'G-GVBLM7438Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCts8CF2wKqW0XIvtNfBnFuqAa11ANKgH8',
    appId: '1:1089220401823:android:2782f2d2cd25937476a0aa',
    messagingSenderId: '1089220401823',
    projectId: 'fasilitas-umum-eeb07',
    storageBucket: 'fasilitas-umum-eeb07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmkNcllgQBXoRRbECyqi0D5fUYH0LYB-c',
    appId: '1:1089220401823:ios:e7f245251a6e938276a0aa',
    messagingSenderId: '1089220401823',
    projectId: 'fasilitas-umum-eeb07',
    storageBucket: 'fasilitas-umum-eeb07.firebasestorage.app',
    iosBundleId: 'com.example.fasilitasUmum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmkNcllgQBXoRRbECyqi0D5fUYH0LYB-c',
    appId: '1:1089220401823:ios:e7f245251a6e938276a0aa',
    messagingSenderId: '1089220401823',
    projectId: 'fasilitas-umum-eeb07',
    storageBucket: 'fasilitas-umum-eeb07.firebasestorage.app',
    iosBundleId: 'com.example.fasilitasUmum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCll-PmzXqvT0j5AocEWjN8ESc-l4CaCFU',
    appId: '1:1089220401823:web:cbb6505d394074de76a0aa',
    messagingSenderId: '1089220401823',
    projectId: 'fasilitas-umum-eeb07',
    authDomain: 'fasilitas-umum-eeb07.firebaseapp.com',
    storageBucket: 'fasilitas-umum-eeb07.firebasestorage.app',
    measurementId: 'G-6DYRBYCY0H',
  );
}
